#!/bin/bash
# Title: Audit Reporter
# Author: bad-antics
# Description: Generates a professional WiFi security audit report with risk scoring and recommendations
# Category: nullsec/blue-team

PROMPT "AUDIT REPORTER

WiFi Security Assessment
Report Generator.

Scans environment and
creates a detailed report:

- Risk scoring
- Security breakdown
- Findings & recommendations
- Full network inventory

Scan: 30 seconds

Press OK to audit."

[ ! -d "/sys/class/net/wlan0" ] && { ERROR_DIALOG "wlan0 not found!"; exit 1; }

OUTDIR="/mmc/nullsec/blue-team/audit-reporter"
mkdir -p "$OUTDIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT="$OUTDIR/audit_${TIMESTAMP}.txt"

SPINNER_START "Security assessment scan (30s)..."
timeout 30 airodump-ng wlan0 -w /tmp/audit --output-format csv 2>/dev/null
SPINNER_STOP

CSV="/tmp/audit-01.csv"
[ ! -f "$CSV" ] && { ERROR_DIALOG "No scan data!"; exit 1; }

SPINNER_START "Generating audit report..."

TOTAL=$(grep -cE "^([0-9A-Fa-f]{2}:){5}" "$CSV" 2>/dev/null || echo 0)
WPA3=$(grep -ci "WPA3" "$CSV" 2>/dev/null || echo 0)
WPA2=$(grep -i "WPA2" "$CSV" 2>/dev/null | grep -cvi "WPA3" || echo 0)
WEP=$(grep -ci "WEP" "$CSV" 2>/dev/null || echo 0)
OPEN=$(grep -E "^([0-9A-Fa-f]{2}:){5}" "$CSV" 2>/dev/null | grep -ci "OPN" || echo 0)
CRITICAL=$((WEP + OPEN))

if [ "$TOTAL" -gt 0 ]; then
    RISK_PCT=$(( (CRITICAL * 100) / TOTAL ))
else
    RISK_PCT=0
fi

if [ "$RISK_PCT" -lt 10 ]; then RISK="LOW"
elif [ "$RISK_PCT" -lt 30 ]; then RISK="MEDIUM"
elif [ "$RISK_PCT" -lt 60 ]; then RISK="HIGH"
else RISK="CRITICAL"
fi

{
    echo "╔══════════════════════════════════════════════════╗"
    echo "║  NullSec WiFi Security Assessment Report        ║"
    echo "╚══════════════════════════════════════════════════╝"
    echo ""
    echo "Date:     $(date '+%B %d, %Y %H:%M')"
    echo "Tool:     NullSec Pineapple Suite"
    echo "Device:   WiFi Pineapple Pager"
    echo ""
    echo "═══ EXECUTIVE SUMMARY ═════════════════════════════"
    echo ""
    echo "  Total Networks:    $TOTAL"
    echo "  Risk Level:        $RISK ($RISK_PCT%)"
    echo "  Critical Findings: $CRITICAL"
    echo ""
    echo "═══ SECURITY DISTRIBUTION ═════════════════════════"
    echo ""
    echo "  WPA3 (Strongest):  $WPA3"
    echo "  WPA2 (Standard):   $WPA2"
    echo "  WEP (Broken):      $WEP"
    echo "  Open (No Auth):    $OPEN"
    echo ""
    echo "═══ FINDINGS ══════════════════════════════════════"
    echo ""
    [ "$OPEN" -gt 0 ] && echo "  [CRITICAL] $OPEN open network(s) — no encryption" && echo "  → Enable WPA3-SAE or WPA2-PSK" && echo ""
    [ "$WEP" -gt 0 ] && echo "  [HIGH] $WEP WEP network(s) — trivially broken" && echo "  → Upgrade to WPA3 or WPA2" && echo ""
    [ "$WPA3" -eq 0 ] && [ "$TOTAL" -gt 0 ] && echo "  [MEDIUM] No WPA3 adoption detected" && echo "  → Plan WPA3 migration" && echo ""
    [ "$CRITICAL" -eq 0 ] && echo "  No critical findings." && echo ""
    echo "═══ NETWORK INVENTORY ═════════════════════════════"
    echo ""
    printf "  %-18s  %-4s  %-6s  %-12s  %s\n" "BSSID" "CH" "PWR" "SECURITY" "ESSID"
    echo "  ─────────────────  ────  ──────  ────────────  ──────────"
    grep -E "^([0-9A-Fa-f]{2}:){5}" "$CSV" | sort -t',' -k9 -n -r | \
        awk -F',' '{gsub(/^ +| +$/,"",$1); gsub(/^ +| +$/,"",$4); gsub(/^ +| +$/,"",$6); gsub(/^ +| +$/,"",$9); gsub(/^ +| +$/,"",$14); printf "  %-18s  %-4s  %-6s  %-12s  %s\n", $1, $4, $9" dBm", $6, ($14=="" ? "<hidden>" : $14)}'
    echo ""
    echo "═══════════════════════════════════════════════════"
    echo "  For authorized security testing only."
    echo "  Generated by NullSec Pineapple Suite"
    echo "  © 2024-2026 bad-antics • NullSec Security"
} > "$REPORT"

SPINNER_STOP

rm -f /tmp/audit* 2>/dev/null

CONFIRMATION_DIALOG "📄 Audit Report Generated\n\nNetworks: $TOTAL\nRisk Level: $RISK ($RISK_PCT%)\nCritical: $CRITICAL\n\nReport: $REPORT"
